name: OpenCloud
version: "0.1.0"
slug: opencloud
description: OpenCloud Filesharing Server
url: https://github.com/d-shmt/ha-opencloud-addon
arch:
  - amd64
  - arm64
startup: services
boot: auto

options:
  data_path: /share/opencloud/data
  config_path: /share/opencloud/config
  external_url: https://cloud.example.com

schema:
  data_path: str
  config_path: str
  external_url: str

ports:
  8080/tcp: null

map:
  - share:rw
  - ssl:rw
