name: "OpenCloud"
version: "1.0.7" # Version hochzählen erzwingt Update
slug: "opencloud"
description: "OpenCloud via NFS"
url: "https://github.com/opencloud-eu/opencloud"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
ports:
  9200/tcp: 9200
map:
  - config:rw
  - share:rw

# DIESER BLOCK IST ENTSCHEIDEND FÜR NFS MOUNT:
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - DAC_READ_SEARCH

options:
  admin_password: "ChangeMe123!"
  oc_url: "https://cloud.deine-domain.de"
  data_path: "10.0.0.100:/HDD/opencloud-data/blobs" # Standard-Beispiel
schema:
  admin_password: password
  oc_url: str
  data_path: str # Wir nutzen weiter data_path
