name: "OpenCloud"
description: "OpenCloud - Filemanagement & Sharing (NAS Support)."
version: "1.1.0"
slug: "opencloud"
init: false
arch:
  - aarch64
  - amd64
ports:
  9200/tcp: 9200
map:
  - share:rw  # WICHTIG: Gibt dem Add-on Zugriff auf /share (wo das NAS liegt)
options:
  admin_password: "changeme"
  data_path: "/data/opencloud" # Standard: Lokal auf HA Disk
schema:
  admin_password: str
  data_path: str # Der Pfad, wo die Daten liegen sollen
startup: application
