name: "OpenCloud (OCIS)"
version: "0.0.2"          # <--- Ã„ndere die Version auf 1.0.1, damit HA das Update erkennt!
slug: "opencloud_ocis"
description: "Run OpenCloud Infinite Scale with Hybrid Storage (NAS/NFS) support."
url: "https://github.com/d-shmt/ha-opencloud-addon"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
map:
  - "share:rw"
ports:
  9200/tcp: 9200
options:
  oc_url: "https://deine-domain.de"
  data_path: "/share/Cloud"
  admin_password: "ChangeMe123!"
schema:
  oc_url: url
  data_path: str
  admin_password: password
