name: "OpenCloud"
version: "0.1.0"
slug: "opencloud"
description: "OpenCloud running as a Home Assistant Add-on."
url: "https://github.com/opencloud-eu"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
map:
  - share:rw  # WICHTIG: Lese-/Schreibzugriff auf /share (wo dein NFS liegt)
ports:
  9200/tcp: 9200
options:
  domain: "cloud.deinedomain.de"
  storage_path: "/share/nas_mount/opencloud_data"
schema:
  domain: str
  storage_path: str
