name: "OpenCloud"
description: "OpenCloud - Filemanagement & Sharing (NAS Support)."
version: "1.2.0"  # Version erh√∂ht
slug: "opencloud"
init: false
arch:
  - aarch64
  - amd64
ports:
  9200/tcp: 9200
map:
  - share:rw
options:
  admin_password: "changeme"
  data_path: "/data/opencloud"
  server_domain: "192.168.1.X" # NEU: Hier muss deine HA-IP rein
schema:
  admin_password: str
  data_path: str
  server_domain: str # NEU
startup: application
