name: "OpenCloud"
version: "1.0.1"  # Version hochzählen!
slug: "opencloud"
description: "Sichere und schnelle Cloud-Lösung"
url: "https://github.com/opencloud-eu/opencloud"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
ports:
  9200/tcp: 9200
map:
  - config:rw
  - share:rw    # <--- WICHTIG: Das erlaubt Zugriff auf das NAS (wenn als "Share" gemountet)
  - media:rw    # Optional, falls du es als "Medien" gemountet hast
options:
  admin_password: "ChangeMe123!"
  oc_url: "https://cloud.datoh.de"
  data_path: "/share/Cloud"  # Standard: Intern
schema:
  admin_password: password
  oc_url: str
  data_path: str           # Der User kann hier einen Pfad eintragen