name: "OpenCloud"
version: "0.0.4"  
slug: "opencloud"
description: "Sichere und schnelle Cloud-LÃ¶sung"
url: "https://github.com/opencloud-eu/opencloud"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
ports:
  9200/tcp: 9200
map:
  - config:rw
  - share:rw    
  - media:rw    
options:
  admin_password: "ChangeMe123!"
  oc_url: "https://your-domain.com"
  data_path: "/share/OpenCloud"  
schema:
  admin_password: password
  oc_url: str
  data_path: str          
