name: "OpenCloud"
version: "1.1.0"
slug: "opencloud"
description: "OpenCloud Rolling Release - Hybrid Storage (Config Local, Blobs NAS)"
url: "https://github.com/opencloud-eu/opencloud"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
ports:
  9200/tcp: 9200
map:
  - share:rw     # Zwingend f√ºr NAS Zugriff
options:
  admin_password: "ChangeMe123!"
  oc_url: "https://cloud.deinedomain.de"
  data_path: "/share/opencloud_data"
schema:
  admin_password: password
  oc_url: str
  data_path: str
