name: "OpenCloud"
version: "4.0.0"
slug: "opencloud"
description: "Self-hosted Cloud basierend auf OCIS Architektur."
url: "https://github.com/opencloud-eu"
arch:
  - aarch64
  - amd64
startup: services
boot: auto
map:
  - config:rw
  - share:rw
  - media:rw
ports:
  9200/tcp: 9200
options:
  oc_domain: "cloud.local"
  initial_admin_password: "changeme"
  log_level: "info"
  oc_insecure: true
  trusted_proxies:
    - "172.30.33.0/24"
    - "127.0.0.1"
schema:
  oc_domain: str
  initial_admin_password: str
  log_level: list(debug, info, warn, error)
  oc_insecure: bool
  trusted_proxies:
    - str
